name: app_nhan_dien_switch
description: "Detect Switch using YOLOv11 in AR"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # AR Core plugin
  arcore_flutter_plugin: ^0.1.0 
  
  # YOLO AI detection
  flutter_vision: ^1.0.0
  
  # Permission handling
  permission_handler: ^11.3.0
  
  # Screenshot capture
  screenshot: ^3.0.0 
  
  # Path provider
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/detect.tflite
    - assets/labelmap.txt 